name: Build a docker container

on:
  push:
    branches:
      - o32
      - o32tools
      - o64
      - o64tools
      - n32
      - n64

# see: https://github.com/marketplace/actions/build-and-push-docker-images
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/toolchain64:${{ github.ref_name }}
