name: Build a docker container

on:
  push:
    branches:
      - o32
      - o32tools
      - o64
      - o64tools
      - n32
      - n64

# see: https://github.com/marketplace/actions/build-and-push-docker-images
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325  # v2.2.1
      - uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a  # v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: SimenB/github-actions-cpu-cores@ecaed1e931b8dd412cf251eadb6f5a69f7101f11  # v1.0.2
        id: cpucores
      - uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5  # v3.2.0
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/toolchain64:${{ github.ref_name }}
          file: Dockerfile.libdragon-n64tools
          build-args: JOBS=${{ steps.cpucores.outputs.count }}
